exclude: ["CNAME", "Gemfile", "Gemfile.lock"]
name: "金数据帮助中心"
url: http://help.jinshuju.net/
markdown: redcarpet
pygments: true
permalink: /articles/:title.html
safe: true
category_dict:
  quickstart: "快速学习金数据"
  form: "表单编辑与管理"
  publish: "表单的发布与分享"
  data: "数据以及报表"
  notification: "短信和邮件提醒"
  wechat: "金数据与微信"
  account: "充值、套餐与增值服务"
  payment: "商品字段和支付"
  api: "API与集成"
gems:
  - jemoji